// Generated by CoffeeScript 1.8.0
var b, cleanup, high, initMode, knight, lo, out, setLED, u0, u1, u2, u3, uArray, usbbase;

b = require('bonescript');

usbbase = '/sys/class/leds/beaglebone:green:usr';

high = b.HIGH;

lo = b.LOW;

out = b.OUTPUT;

u0 = 'USR0';

u1 = 'USR1';

u2 = 'USR2';

u3 = 'USR3';

uArray = [];

uArray.push(u0);

uArray.push(u1);

uArray.push(u2);

uArray.push(u3);

initMode = function() {
  var led, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = uArray.length; _i < _len; _i++) {
    led = uArray[_i];
    _results.push(b.pinMode(led, out));
  }
  return _results;
};

setLED = function(pinnum, onMode, cb, delay) {
  var setOff, setOn;
  setOff = function() {
    return b.digitalWrite(uArray[pinnum], lo);
  };
  setOn = function() {
    return b.digitalWrite(uArray[pinnum], high);
  };
  if (!onMode) {
    setOff();
  } else {
    setOn();
  }
  if (cb) {
    setTimeout(cb, delay);
  }
};

cleanup = function() {
  var i, _i, _len, _ref;
  _ref = uArray.length;
  for (_i = 0, _len = _ref.length; _i < _len; _i += 1) {
    i = _ref[_i];
    setLED(1, false);
  }
};

knight = function() {
  var count, currDirection, currLed, delayTime, hiLed, lowLed, maxInterations, worker;
  delayTime = 100;
  maxInterations = 300;
  count = 0;
  hiLed = 3;
  lowLed = 0;
  currLed = 0;
  currDirection = 1;
  initMode();
  cleanup();
  worker = function() {
    count += 1;
    if (count > maxInterations) {
      cleanup();
      return;
    }
    setLED(currLed, false);
    currLed += currDirection;
    if (currLed > hiLed) {
      currDirection = -1;
      currLed = hiLed + currDirection;
    } else if (currLed < lowLed) {
      currDirection = 1;
      currLed = lowLed + currDirection;
    }
    setLED(currLed, true, worker, delayTime);
  };
  worker();
};

knight();
